apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-secret-demo
  template:
    metadata:
      labels:
        app: my-app-secret-demo
    spec:
      containers:
        - name: app
          image: nginx:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: app-config
              mountPath: /etc/app-config
      volumes:
        - name: app-config
          configMap:
            name: my-app-config